version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: VentaPostgres
    ports:
      - "5498:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data:
    driver: local
